// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca_test.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ca_5ftest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ca_5ftest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ca_5ftest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ca_5ftest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ca_5ftest_2eproto;
class CaTestInfoAck;
class CaTestInfoAckDefaultTypeInternal;
extern CaTestInfoAckDefaultTypeInternal _CaTestInfoAck_default_instance_;
class CaTestInfoReq;
class CaTestInfoReqDefaultTypeInternal;
extern CaTestInfoReqDefaultTypeInternal _CaTestInfoReq_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CaTestInfoAck* Arena::CreateMaybeMessage<::CaTestInfoAck>(Arena*);
template<> ::CaTestInfoReq* Arena::CreateMaybeMessage<::CaTestInfoReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CaTestInfoReq :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CaTestInfoReq) */ {
 public:
  CaTestInfoReq();
  virtual ~CaTestInfoReq();

  CaTestInfoReq(const CaTestInfoReq& from);
  CaTestInfoReq(CaTestInfoReq&& from) noexcept
    : CaTestInfoReq() {
    *this = ::std::move(from);
  }

  inline CaTestInfoReq& operator=(const CaTestInfoReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CaTestInfoReq& operator=(CaTestInfoReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CaTestInfoReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CaTestInfoReq* internal_default_instance() {
    return reinterpret_cast<const CaTestInfoReq*>(
               &_CaTestInfoReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CaTestInfoReq& a, CaTestInfoReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CaTestInfoReq* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CaTestInfoReq* New() const final {
    return CreateMaybeMessage<CaTestInfoReq>(nullptr);
  }

  CaTestInfoReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CaTestInfoReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CaTestInfoReq& from);
  void MergeFrom(const CaTestInfoReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CaTestInfoReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CaTestInfoReq";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ca_5ftest_2eproto);
    return ::descriptor_table_ca_5ftest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTestNumFieldNumber = 1,
  };
  // uint32 test_num = 1;
  void clear_test_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 test_num() const;
  void set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_test_num() const;
  void _internal_set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CaTestInfoReq)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 test_num_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ca_5ftest_2eproto;
};
// -------------------------------------------------------------------

class CaTestInfoAck :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CaTestInfoAck) */ {
 public:
  CaTestInfoAck();
  virtual ~CaTestInfoAck();

  CaTestInfoAck(const CaTestInfoAck& from);
  CaTestInfoAck(CaTestInfoAck&& from) noexcept
    : CaTestInfoAck() {
    *this = ::std::move(from);
  }

  inline CaTestInfoAck& operator=(const CaTestInfoAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline CaTestInfoAck& operator=(CaTestInfoAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CaTestInfoAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CaTestInfoAck* internal_default_instance() {
    return reinterpret_cast<const CaTestInfoAck*>(
               &_CaTestInfoAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CaTestInfoAck& a, CaTestInfoAck& b) {
    a.Swap(&b);
  }
  inline void Swap(CaTestInfoAck* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CaTestInfoAck* New() const final {
    return CreateMaybeMessage<CaTestInfoAck>(nullptr);
  }

  CaTestInfoAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CaTestInfoAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CaTestInfoAck& from);
  void MergeFrom(const CaTestInfoAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CaTestInfoAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CaTestInfoAck";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ca_5ftest_2eproto);
    return ::descriptor_table_ca_5ftest_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJsonDataFieldNumber = 2,
    kTestNumFieldNumber = 1,
  };
  // string json_data = 2;
  void clear_json_data();
  const std::string& json_data() const;
  void set_json_data(const std::string& value);
  void set_json_data(std::string&& value);
  void set_json_data(const char* value);
  void set_json_data(const char* value, size_t size);
  std::string* mutable_json_data();
  std::string* release_json_data();
  void set_allocated_json_data(std::string* json_data);
  private:
  const std::string& _internal_json_data() const;
  void _internal_set_json_data(const std::string& value);
  std::string* _internal_mutable_json_data();
  public:

  // uint32 test_num = 1;
  void clear_test_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 test_num() const;
  void set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_test_num() const;
  void _internal_set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CaTestInfoAck)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr json_data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 test_num_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ca_5ftest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CaTestInfoReq

// uint32 test_num = 1;
inline void CaTestInfoReq::clear_test_num() {
  test_num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CaTestInfoReq::_internal_test_num() const {
  return test_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CaTestInfoReq::test_num() const {
  // @@protoc_insertion_point(field_get:CaTestInfoReq.test_num)
  return _internal_test_num();
}
inline void CaTestInfoReq::_internal_set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  test_num_ = value;
}
inline void CaTestInfoReq::set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_test_num(value);
  // @@protoc_insertion_point(field_set:CaTestInfoReq.test_num)
}

// -------------------------------------------------------------------

// CaTestInfoAck

// uint32 test_num = 1;
inline void CaTestInfoAck::clear_test_num() {
  test_num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CaTestInfoAck::_internal_test_num() const {
  return test_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CaTestInfoAck::test_num() const {
  // @@protoc_insertion_point(field_get:CaTestInfoAck.test_num)
  return _internal_test_num();
}
inline void CaTestInfoAck::_internal_set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  test_num_ = value;
}
inline void CaTestInfoAck::set_test_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_test_num(value);
  // @@protoc_insertion_point(field_set:CaTestInfoAck.test_num)
}

// string json_data = 2;
inline void CaTestInfoAck::clear_json_data() {
  json_data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CaTestInfoAck::json_data() const {
  // @@protoc_insertion_point(field_get:CaTestInfoAck.json_data)
  return _internal_json_data();
}
inline void CaTestInfoAck::set_json_data(const std::string& value) {
  _internal_set_json_data(value);
  // @@protoc_insertion_point(field_set:CaTestInfoAck.json_data)
}
inline std::string* CaTestInfoAck::mutable_json_data() {
  // @@protoc_insertion_point(field_mutable:CaTestInfoAck.json_data)
  return _internal_mutable_json_data();
}
inline const std::string& CaTestInfoAck::_internal_json_data() const {
  return json_data_.GetNoArena();
}
inline void CaTestInfoAck::_internal_set_json_data(const std::string& value) {
  
  json_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CaTestInfoAck::set_json_data(std::string&& value) {
  
  json_data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CaTestInfoAck.json_data)
}
inline void CaTestInfoAck::set_json_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  json_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CaTestInfoAck.json_data)
}
inline void CaTestInfoAck::set_json_data(const char* value, size_t size) {
  
  json_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CaTestInfoAck.json_data)
}
inline std::string* CaTestInfoAck::_internal_mutable_json_data() {
  
  return json_data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CaTestInfoAck::release_json_data() {
  // @@protoc_insertion_point(field_release:CaTestInfoAck.json_data)
  
  return json_data_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CaTestInfoAck::set_allocated_json_data(std::string* json_data) {
  if (json_data != nullptr) {
    
  } else {
    
  }
  json_data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), json_data);
  // @@protoc_insertion_point(field_set_allocated:CaTestInfoAck.json_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ca_5ftest_2eproto
